os: linux
language: python
addons:
  apt:
    packages:
    - libzstd1
    - libxcursor-dev
    - libxfixes-dev
    - libxi-dev
    - libgl1-mesa-dev
    - libxrandr-dev
    - libx11-xcb-dev
    - libxcb-keysyms1
    - libxcb-keysyms1-dev
    - libxcb-image0
    - libxcb-image0-dev
    - libxcb-icccm4
    - libxcb-icccm4-dev
    - libxcb-sync-dev
    - libxcb-xfixes0-dev
    - libxcb-shape0-dev
    - libxcb-render-util0-dev
    - libxcb-randr0-dev
    - libxcb-render-util0
    - libxcb-glx0-dev
    - libxcb-xinerama0
    - libxcb-xinerama0-dev
services: xvfb
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
  - pip install conan
  - conan user
env:
  - QT_DEBUG_PLUGINS=1
script:
  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
  - mkdir build && cd build && conan install .. --build Qt && cmake .. && make
  - timeout 10 ./bin/helloworld
