os: linux
language: python
services: xvfb
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
  - pip install conan
  - conan user
env:
  - QT_DEBUG_PLUGINS=1
script:
  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
  - mkdir build && cd build && conan install .. --build Qt && cmake .. && make
  - source activate_run.sh
  - timeout 10 ./bin/helloworld
